### ISSUE TITLE
Plans for 'Deleting artifacts'

### ISSUE THREAD

**Issue by EugenMayer** [hanjos/nexus-cli#1]
Thank you for providing this cli tool, it could be very handy!

Is there any plan to be able to bulk delete artifacts? because right now, that is somehow the biggest burden in the ui and also could need some automation!

Thanks

**Comment by hanjos** [comment]
Wow, thanks! 

No plans, unfortunately... I wrote [hanjos/nexus](https://godoc.org/github.com/hanjos/nexus) (where the heavy lifting is done) and later this tool to help me gather data. But I've since moved to other department, so Nexus hasn't been an itch to scratch in quite some time (it's been almost 3 years now...).

That being said, and off the top of my head, it shouldn't be hard; I can envision a `nexus.DeleteAll(credentials.Credentials, search.Criteria)` function in `hanjos/nexus` doing the necessary REST calls, but cleanup and reindexing might be necessary afterwards. So it could get tricky...

Pull requests are welcome 😁

**Comment by EugenMayer** [comment]
Interesting @hanjos ! does https://godoc.org/github.com/hanjos/nexus provide an interface for any artifact type, also e.g. `raw` and `gem` and even docker? Or let me ask the other way, why not using a maven based, gem based, docker base client instead of using the generic one?

Seems like this would only make a lot of sense for "raw" would it?

**Comment by hanjos** [comment]
[hanjos/nexus](https://godoc.org/github.com/hanjos/nexus) is Maven-only, because my Nexus was OSS and old (_very_ pre-3.0), so Maven was all I needed it to support :)

Its API would definitely need changes to support multiple repository types. That sounds like a fun little exploration (no generics means different designs, properly dealing with massive API breakage, one client per repo type vs one client to rule them all...). 

Alas, my time has been pulled elsewhere...

**Comment by EugenMayer** [comment]
well i do not thing it makes sense having that done manually, that is what a maven client would - it can consume nexus repos but also artifactory and things. I do not really think replicating this makes a lot of sense. Thanks for the explanation thoug!

**Comment by hanjos** [comment]
OK!
